// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-v0JuNaPBTZY_Kblq2pcPzPOgQZvFeDE',
    appId: '1:54748093432:web:1b5d91e1e5bbabf201940d',
    messagingSenderId: '54748093432',
    projectId: 'utsav-app-bloc',
    authDomain: 'utsav-app-bloc.firebaseapp.com',
    storageBucket: 'utsav-app-bloc.appspot.com',
    measurementId: 'G-G8GVTFX82R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi-j8WFmRBjFNokijHhjAemAbq_7Qijwo',
    appId: '1:54748093432:android:91006657972a97ca01940d',
    messagingSenderId: '54748093432',
    projectId: 'utsav-app-bloc',
    storageBucket: 'utsav-app-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjG1_kxDYgCqBy0ZueKIrd2r0lWh6mcWI',
    appId: '1:54748093432:ios:888af6aee786fe6101940d',
    messagingSenderId: '54748093432',
    projectId: 'utsav-app-bloc',
    storageBucket: 'utsav-app-bloc.appspot.com',
    iosBundleId: 'com.example.utsavAppBloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjG1_kxDYgCqBy0ZueKIrd2r0lWh6mcWI',
    appId: '1:54748093432:ios:f08d514f5b001d1301940d',
    messagingSenderId: '54748093432',
    projectId: 'utsav-app-bloc',
    storageBucket: 'utsav-app-bloc.appspot.com',
    iosBundleId: 'com.example.utsavAppBloc.RunnerTests',
  );
}
